all: resume.min.js spinning-wheel.min.js 

resume.min.js: resume.js
	node-minify -c butternut -i resume.js -o resume.min.js
spinning-wheel.min.js: spinning-wheel.js
	node-minify -c butternut -i spinning-wheel.js -o spinning-wheel.min.js
